#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
CLI entry point for automatic panorama creation from a folder of TIFF images.

Usage:
    ./create_panorama.py /path/to/panorama/folder/

The folder should contain 16-bit TIFF files generated by sort_photos.py
(via the RAW processing pipeline for detected panorama groups).

Requires: hugin-tools (provides hsi, cpfind, nona) and enblend.
Platform: Linux x86_64 only.
"""

import logging
import os
import sys

from photo_sorter.panorama import create_panorama

logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s\t%(levelname)s\t%(filename)s:%(lineno)d\t%(message)s')
log = logging.getLogger("create_panorama.py")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        log.critical(f"Usage: {sys.argv[0]} /path/to/panorama/folder/")
        sys.exit(1)

    pano_folder = sys.argv[1]

    if not os.path.isdir(pano_folder):
        log.error(f"Folder '{pano_folder}' does not exist or is not a directory.")
        sys.exit(1)

    success = create_panorama(pano_folder)
    sys.exit(0 if success else 1)
